aparfianiuk/add-publishers
belaudiobooks/website pull request #89
Opened 2023-06-28 03:53 UTC by frombrest

Resolves #59

2023-06-28 04:38 UTC, nbeloglazov requested changes
Looks good! Left few comments. Few should also add webdriver tests. But they are currently rely on database containing actual publishers. So I first need to merge this PR, create few publishers and then we can write tests. Also filed #90 for migrating tests.

2023-06-28 04:38 UTC, nbeloglazov commented on books/views/publisher.py
> +        pass  # TODO: implement 404 page
Let's use `get_object_or_404` here as we do for books: https://github.com/belaudiobooks/website/blob/main/books/views/book.py#L12 I don't know why we use this different pattern for Person view.

2023-06-28 04:38 UTC, nbeloglazov commented on templates/partials/_publisher.html
> +{% load books_extras %}
I don't think we need to load static or books_extras for this page as they are not used?

2023-06-28 04:38 UTC, nbeloglazov commented on books/views/publisher.py
> +        narrations = publisher.narrations.all().filter()
.filter() is reduntant

2023-06-28 04:38 UTC, nbeloglazov commented on books/views/publisher.py
> +            'narrations': narrated_books,
Let's call it `books` rather that `narrations`. Given that it's a list of Book models `books` better reflects what it is.

2023-06-28 04:38 UTC, nbeloglazov commented on templates/books/publisher.html
> +  На гэтай старонке вы знойдзеце ўсе кнігі выданыя альбо агучаныя выдавецтвам {{publisher.name}}.
grammar: старонЦЫ

2023-06-28 04:51 UTC, frombrest commented on templates/books/publisher.html
> +  На гэтай старонке вы знойдзеце ўсе кнігі выданыя альбо агучаныя выдавецтвам {{publisher.name}}.
That is something I wanted to clarify:
старонКЕ ? старонЦЫ
аўдыЯкнігі ? аўдыЁкнігі

2023-06-28 05:22 UTC, nbeloglazov commented on templates/books/publisher.html
> +  На гэтай старонке вы знойдзеце ўсе кнігі выданыя альбо агучаныя выдавецтвам {{publisher.name}}.
старонЦЫ: https://slounik.org/search?dict=&search=%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%BD%D0%BA%D0%B0

І мы выкарыстоўваем аўдыЯкнігі. Шмат хто выкарыстоўвае Ё, але мы вырашылі Я, т.к. гэта больш адпавядае сучаснаму правапісу.

2023-06-28 05:23 UTC, nbeloglazov commented
Ah, and we also should add links to all publishers to the sitemap page: https://github.com/belaudiobooks/website/blob/main/books/views/support.py#L110

2023-06-28 05:47 UTC, frombrest commented
> Ah, and we also should add links to all publishers to the sitemap page: https://github.com/belaudiobooks/website/blob/main/books/views/support.py#L110

Added

2023-06-29 03:52 UTC, nbeloglazov approved these changes

2023-06-29 04:00 UTC, merged